senaite/senaite.patient

src/senaite/patient/__init__.py, src/senaite/patient/adapters/guards.py, src/senaite/patient/adapters/listing.py
This PR ensures that adapters are only called if `senaite.patient` is installed (active). The following traceback arises otherwise:
```
Module senaite.app.listing.view, line 215, in __call__
Module senaite.app.listing.ajax, line 108, in handle_subpath
Module senaite.app.listing.decorators, line 63, in wrapper
Module senaite.app.listing.decorators, line 50, in wrapper
Module senaite.app.listing.decorators, line 100, in wrapper
Module senaite.app.listing.ajax, line 533, in ajax_folderitems
Module senaite.app.listing.decorators, line 88, in wrapper
Module senaite.app.listing.ajax, line 312, in …
```
=> Check if installed when layer-inespecific adapters are called

src/senaite/patient/subscribers/__init__.py, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/subscribers/configure.zcml
This Pull Request adds the `check_installed` decorator to subscribers so they are not called unless `senaite.patient` add-on is installed/active.
Traceback on Sample creation without this PR and with `senaite.patient` add-on not active:
```
Module bika.lims.browser.analysisrequest.add2, line 67, in decorator
Module bika.lims.browser.analysisrequest.add2, line 739, in __call__
Module bika.lims.browser.analysisrequest.add2, line 1691, in ajax_submit
Module bika.lims.utils.analysisrequest, line 84, in create_analysisrequest
Module Products.Archetypes.BaseObject, line 685, in processForm
Module zope.event, …
```
=> Add check_installed decorator to subscribers

src/senaite/patient/skins/templates/senaite_patient_widgets/temporaryidentifierwidget.pt
The `required` attribute flags simply by it's existance if empty form submission is allowed or not.
Therefore, `required="True"` or `required="False"` are both required.
This PR ensures that the required attribute is absent in the MRN field from the sample header view if the patient is optional for samples.
=> Omit required attribute if patient is optional

src/senaite/patient/adapters/listing.py, src/senaite/patient/setuphandlers.py
This Pull Request adds the columns "MRN" (Medical Record Number) and "Patient" (patient's fullname) in Samples listing. It also added these two as metadata fields on samples' catalog so user can search by them too.
=> Added "MRN" and "Patient" columns in Samples listing

src/senaite/patient/adapters/guards.py, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/configure.zcml, src/senaite/patient/upgrade/__init__.py, src/senaite/patient/upgrade/configure.zcml, src/senaite/patient/upgrade/v01_00_000.py
This Pull Request adds these two additional settings in senaite patient's control panel:
-  Allow to verify samples with a temporary MRN (checkbox)
If selected, users will be able to verify samples that have a Patient assigned with a temporary Medical Record Number (MRN).
- Allow to publish samples with a temporary MRN (checkbox) 
If selected, users will be able to publish samples that have a Patient assigned with a temporary Medical Record Number (MRN).
=> Allow/disallow to verify/publish samples with temporary MRN

docs/changelog.rst, src/senaite/patient/browser/widgets.py, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt, src/senaite/patient/subscribers/analysisrequest.py
This PR converts the DoB widget to a native `<input="date" ... />` field.
This makes it compatible with https://github.com/senaite/senaite.core/pull/1892
=> Convert DoB widget to native date input field

src/senaite/patient/browser/widgets.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt, src/senaite/patient/skins/templates/senaite_patient_widgets/fullnamewidget.pt
This PR renders the fullname and dob widgets as [input-groups](https://getbootstrap.com/docs/4.6/components/input-group)
=> Improve widget markup

src/senaite/patient/upgrade/v01_00_000.py
Fixture for https://github.com/senaite/senaite.patient/pull/24
This PR removes the `api.is_folderish` check in the upgrade step, because it tests the base class of the object and not the object itself. Therefore, it is always `True` although the object is contentish.
=> Remove folderish check in upgrade step

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, docs/changelog.rst, src/senaite/patient/content/patient.py
This Pull Request allows the creation of Samples without Patient ID being set.
The following traceback arises on Add Sample form submit when a value for "Patient ID" field is not set:
```
Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 371, in publish_module
Module ZPublisher.WSGIPublisher, line 274, in publish
Module bika.lims.browser.analysisrequest.add2, line 72, in decorator
Module bika.lims.browser.analysisrequest.add2, line 709, in __call__
Module bika.lims.browser.analysisrequest.add2, line 1642, in ajax_submit
Module bika.lims.utils.analysisrequest, line 84, in create_analysisrequest
Module …
```
=> Fix cannot create samples with empty Patient ID

docs/changelog.rst, src/senaite/patient/browser/widgets.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This PR changes the age/dob selection method
age/dob selection changed in widget (for all entities)
age/dob selection remembered on context
--
=> Remember age/dob selection on context

docs/changelog.rst, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/catalog/configure.zcml, src/senaite/patient/catalog/indexers.py, src/senaite/patient/catalog/patient_catalog.py, src/senaite/patient/content/patient.py, src/senaite/patient/upgrade/v01_01_000.py
**Please merge https://github.com/senaite/senaite.core/pull/1931 first**
The code of this PR has changed to rely only on the setter from the datetime field.
This PR avoids that the following traceback occurs:
Module senaite.app.listing.view, line 223, in __call__
Module senaite.app.listing.ajax, line 109, in handle_subpath
Module senaite.core.decorators, line 20, in decorator
Module senaite.app.listing.decorators, line 63, in wrapper
Module senaite.app.listing.decorators, line 50, in wrapper
Module senaite.app.listing.decorators, line 100, in wrapper
Module senaite.app.listing.ajax, line 432, in …
=> Avoid UnknownTimeZoneError when creating patient from Sample

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/catalog/configure.zcml, src/senaite/patient/catalog/indexers.py, src/senaite/patient/catalog/patient_catalog.py, src/senaite/patient/config.py, src/senaite/patient/configure.zcml, src/senaite/patient/content/__init__.py, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/content/fields.py, src/senaite/patient/content/patient.py, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/tests/doctests/PatientWorkflow.rst, src/senaite/patient/upgrade/v01_01_000.py, src/senaite/patient/vocabularies.py
This PR adds configurable identifiers for patients.
Identifiers can be e.g. Drivers License, Voter ID, Passport ID etc.
and can be configured in the Patient setup:
Multiple identifiers can then be added to a patient:
Note: Identifiers that are in use can not be deleted! Only the title can be changed afterwards.
No identifiers for patients available
Identifiers can be configured for patients
--
=> Add Patient Identifiers

docs/changelog.rst, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/catalog/configure.zcml, src/senaite/patient/catalog/indexers.py, src/senaite/patient/catalog/patient_catalog.py, src/senaite/patient/content/patient.py, src/senaite/patient/subscribers/analysisrequest.py
**☝️ NOTE** Please merge https://github.com/senaite/senaite.patient/pull/30 first!
This PR allows to include the patient email into the sample CC emails to receive result reports:
Patient email not included in result reports
Patient email automatically included in sample CC emails when the email report option is set for a patient
--
=> Allow patient to receive result reports

buildout.cfg, src/senaite/patient/api.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/catalog/indexers.py, src/senaite/patient/content/patient.py, src/senaite/patient/subscribers/patient.py, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/upgrade/v01_00_000.py, src/senaite/patient/upgrade/v01_01_000.py
This PR refactors the getters/setters to use the schema accessors/mutators.
Patient setters/getters wrote values directly on the attribute
Patient setters/getters use the schema accessors/mutators
--
=> Refactor getter setters

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/catalog/indexers.py, src/senaite/patient/content/patient.py, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/upgrade/v01_01_000.py
This Pull Request allows to store values with special characters on patient fields. It also ensures Patient fields behave as the safest convention regarding unicode and encoded strings that is as follows:
- field values are stored as unicode
- accessors return encoded strings
- catalog indexes store encoded strings
See https://community.plone.org/t/item-indexes-cause-catalog-rebuild-to-fail/4927
```
Module ZPublisher.WSGIPublisher, line 168, in transaction_pubevents
Module transaction._manager, line 257, in commit
Module transaction._manager, line 134, in commit
Module transaction._transaction, line 267, in commit
Module transaction._transaction, line 333, in _callBeforeCommitHooks
Module transaction._transaction, line 372, in _call_hooks
Module …
```
=> Fix UnicodeDecodeError when storing Patient name with special chars

docs/changelog.rst, src/senaite/patient/profiles/default/workflows.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_folder_workflow/definition.xml, src/senaite/patient/upgrade/v01_01_000.py
This Pull Request updatest the workflow bound to "Patients" root folder so it is only displayed to users from laboratory
Linked issue: https://github.com/senaite/senaite.patient/issues/
Client contacts can see Patients root folder link
The Patients folder link is only visible to laboratory contacts
--
=> Do not display Patient root folder to users other than lab contacts

docs/changelog.rst, src/senaite/patient/profiles/default/rolemap.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_folder_workflow/definition.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_workflow/definition.xml, src/senaite/patient/upgrade/v01_01_000.py
This Pull Request ensures that client users can create patients and samples.
An error arises when client users try to create a Sample with patient information. The sample without patient information is created in the background without the user being noticed, but without information regarding patient.
- The sample is created properly, with information about the patient
- Client user can navigate to Patients and see the Patients he/she created and edit them
- Client user cannot see Patients created by other users
--
=> Allow client users to create samples and patients

docs/changelog.rst, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/content/patient.py, src/senaite/patient/profiles/default/rolemap.xml, src/senaite/patient/profiles/default/types/Patient.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_folder_workflow/definition.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_workflow/definition.xml, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/tests/base.py, src/senaite/patient/tests/doctests/PatientWorkflow.rst, src/senaite/patient/upgrade/v01_01_000.py
**Please merge https://github.com/senaite/senaite.patient/pull/37 and https://github.com/senaite/senaite.core/pull/2004 first**
This Pull Request makes possible to share patients across users from different clients. Also, system can be configured so patients are automatically shared with sample's client users when a sample with patient information is created.
- Cannot share patients across client users
- Patients created on sample creation are not visible to users from the client the sample belongs to
- Can share patients across client users
- System can be configured so patients created on sample creation become visible to users from the client the sample belongs to
--
and [Plone's Python styleguide][2] …
=> Allow to share patients across clients

src/senaite/patient/adapters/listing.py, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/upgrade/v01_02_000.py
This Pull Request adds a new setting in patient's control panel that makes possible to hide/display the alert icon for temporary MRN on sampls listing
An alert icon is displayed for samples with a temporary MRN
An alert icon is displayed for samples with a temporary MRN, but only if the setting is enabled
--
=> Add setting to display/hide temporary MRN icon in samples listing

docs/changelog.rst, src/senaite/patient/profiles/default/types/Patient.xml, src/senaite/patient/upgrade/v01_03_000.py
This Pull Request removes the "patients" action from inside "Patient" type
"Patients" action link is displayed in Patient's view
"Patients" action link is not displayed in Patient's view
--
=> Remove patients action link from inside Patient type

docs/changelog.rst, src/senaite/patient/tests/base.py
This Pull Request removes the `Products.TextIndexNG3` dependency on the test layer because it is no longer a SENAITE dependency as per https://github.com/senaite/senaite.core/pull/2011 and https://github.com/senaite/senaite.core/pull/2014
--
=> Remove dependency to Products.TextIndexNG3 (test layer)

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/widgets.py, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This Pull Request adds a new configuration option "Age" in patient's control panel. If the option is not selected, the introduction of Age won't be allowed, but Date of birth only
Users can set either the age or date of birth when registering samples
Users can set the age or date of birth when registering samples in accordance with the new configuration option
--
=> Added configuration option for Age introduction

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/widgets.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This Pull Request adds the "Age in years" configuration option in patient's control panel that makes the system "hide" the month and days from the Age widget when the patient is older than 1 year
When the option is selected, only the year is displayed if older than 1 year:
Otherwise, all input fields are displayed. The styling of the widget has been improved as well, so the labels for "Years", "Months" and "Days" are always visible now (they are not placeholders anymore)
Months and days are always displayed on "Age" widget
Months and days are only displayed if the patient is younger than 1 year or if the configuration option "Age in years" is disabled
--
[1]: …
=> Added config option to hide age's month and day when older than 1 year

docs/changelog.rst, src/senaite/patient/browser/controlpanel.py
This PR adds fielsets to the patient controlpanel for better handling
Patient controlpanel showed all fields on one page
Patient controlpanel groups fields into meaningful fieldsets
--
=> Group configuration settings

docs/changelog.rst, src/senaite/patient/browser/widgets.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This Pull Request adds a prominent label with the text "Estimated" next to the Date of Birth widget when the value is estimated from the value entered for Age. 
Is not possible to know if the date of birth was estimated by the system from the age or it was actually entered by the user
System clearly indicates when the date of birth was estimated from age and when was entered manually
--
=> Display "Estimated" next to date of birth when estimated from age

docs/changelog.rst, src/senaite/patient/content/patient.py, src/senaite/patient/tests/doctests/Patient.rst
This PR adds a new datagrid field to add multiple additional email addresses.
Only one email address possible for a patient
Multiple (named) email addresses can be stored per patient
--
=> Allow additional email addresses for patients

docs/changelog.rst, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/catalog/configure.zcml, src/senaite/patient/catalog/indexers.py, src/senaite/patient/catalog/patient_catalog.py, src/senaite/patient/config.py, src/senaite/patient/configure.zcml, src/senaite/patient/content/patient.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/upgrade/configure.zcml, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml, src/senaite/patient/vocabularies.py
This PR adds a new field to track the patient marital status:
The default available marital statuses are defined according to http://hl7.org/fhir/R4/valueset-marital-status.html
This list can be modified in the patient control panel:
Marital status not tracked for patients
Marital status is tracked for patients
--
=> Add patient marital status

docs/changelog.rst, src/senaite/patient/browser/configure.zcml, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/views.py
This PR makes the Patient MRN field optional in Add/Edit forms, if it is not set to mandatory in Patient setup:
MRN was always required
MRN is not required if not set as mandatory in patient setup
--
=> Optional MRN in Patient Add/Edit forms

docs/changelog.rst, src/senaite/patient/content/patient.py, src/senaite/patient/content/schema.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
**NOTE ☝️: This PR requires https://github.com/senaite/senaite.core/pull/2165**
This PR allows to set additional named phone numbers per patient in a proper number format.
Only 2 emails allowed per patient
Multiple emails are allowed per patient
--
=> Allow to set additional named phone numbers

docs/changelog.rst, src/senaite/patient/content/patient.py
This PR fixes the following error that might occur for some timezones:
```
Module senaite.app.listing.view, line 236, in __call__
Module senaite.app.listing.ajax, line 112, in handle_subpath
Module senaite.core.decorators, line 22, in decorator
Module senaite.app.listing.decorators, line 63, in wrapper
Module senaite.app.listing.decorators, line 50, in wrapper
Module senaite.app.listing.decorators, line 100, in wrapper
Module senaite.app.listing.ajax, line 460, in ajax_folderitems
Module senaite.app.listing.decorators, line 88, in wrapper
Module senaite.app.listing.ajax, line 339, in get_folderitems …
```
=> Fix unknown timezone error for birthdate in patient listing

docs/changelog.rst, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/validators.py
**Please merge #57 first**
This PR adds a sample field validator when for the patient ID if the value was changed in the sample directly (over the sample header viewlet).
NOTE: This PR requires https://github.com/senaite/senaite.core/pull/2169 so that the field is properly indicated in the sample header viewlet
`ValueError` occured when the patient ID was not unique -> Viewlet rendered an error
Patient ID is properly validated if it does not belong to the same patient MRN.
--
=> Add sample field validation for patient ID

docs/changelog.rst, src/senaite/patient/content/fields.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
When the patient name entry mode is set to "parts" (*First name + Last name*) in Patient settings, an input text area for the middle name is displayed in Add form, but the value is not kept later in samples listings, that in turn causes the system to alert that the patient name from the sample does not match with the "real" patient name
Patient middle name is not displayed as part of the patient's fullname in sample listings
Patient middle name is displayed as part of the patient's fullname in sample listings
--
=> Fix patient's middlename is not displayed in samples listing

docs/changelog.rst, src/senaite/patient/adapters/listing.py
This Pull Request fixes a traceback that occurs when a patient with special characters in its fullname is registered in the system on sample creation and the patient fullname is changed in the sample afterwards. In such case, the system is meant to display an alert stating that the name of the patient set for the sample does not match with the name of the underlying patient
```
Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 371, in publish_module
Module ZPublisher.WSGIPublisher, line 274, in publish
Module senaite.app.listing.view, line 236, in __call__
Module senaite.app.listing.ajax, line 112, in …
```
=> Fix Traceback in listing when fullname is different from sample's

docs/changelog.rst, src/senaite/patient/browser/patient/add2.py, src/senaite/patient/config.py, src/senaite/patient/skins/templates/senaite_patient_widgets/fullnamewidget.pt
This Pull Request adds another option in name entry modes: "First + last"
Two name entry modes available: "Fullname" and "First + middle + last"
Three name entry modes available: "Fullname", "First + last" and "First + middle + last"
--
=> Added new name entry mode (firstname + lastname)

docs/changelog.rst, src/senaite/patient/browser/patient/samples.py
This Pull Request fixes a Traceback in patient's samples listing when the name of the patient contains special characters (e.g. "Ramón Turró")
```
Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 371, in publish_module
Module ZPublisher.WSGIPublisher, line 250, in publish
Module ZPublisher.BaseRequest, line 518, in traverse
Module ZPublisher.BaseRequest, line 349, in traverseName
Module plone.dexterity.browser.traversal, line 52, in publishTraverse
Module ZPublisher.BaseRequest, line 117, in publishTraverse
Module zope.component._api, line 116, in queryMultiAdapter
Module zope.interface.registry, line 365, in queryMultiAdapter
Module zope.interface.adapter, line 844, in queryMultiAdapter
Module …
```
=> Fix Traceback in patient's samples view when name has special characters

docs/changelog.rst, src/senaite/patient/content/fields.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/skins/templates/senaite_patient_widgets/fullnamewidget.pt, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
This Pull Request fixes an *error while rendering senaite.core.sampleheader* in sample view when the sample does not have a middle name set.
An *error while rendering senaite.core.sampleheader* is displayed instead of a sample header
The sample header is displayed correctly
--
=> Fix samples without patient middle name

docs/changelog.rst, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt, src/senaite/patient/skins/templates/senaite_patient_widgets/fullnamewidget.pt
This PR fixes the view mode of the fullname- and dob widget.
NOTE: This PR depends on https://github.com/senaite/senaite.core/pull/2280
Tracebacks occur when rendering the sample header in view mode, e.g. for an Analyst
Fullname- and DoB widgets render correctly in view mode
--
=> Fix widget view mode

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/client/configure.zcml, src/senaite/patient/browser/client/patients.py, src/senaite/patient/browser/configure.zcml, src/senaite/patient/browser/controlpanel.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/subscribers/configure.zcml, src/senaite/patient/subscribers/controlpanel.py, src/senaite/patient/tests/base.py, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
This PR allows to create patients inside client folders when enabled:
Patients can be only created in global Patients folder
Patients can be created in clients folder as well
--
=> Allow client local patients

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/configure.zcml, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/configure.zcml, src/senaite/patient/permissions.py, src/senaite/patient/permissions.zcml, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/profiles/default/rolemap.xml, src/senaite/patient/profiles/default/types/PatientFolder.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_folder_workflow/definition.xml, src/senaite/patient/profiles/default/workflows/senaite_patient_workflow/definition.xml, src/senaite/patient/skins/templates/senaite_patient_widgets/temporaryidentifierwidget.pt, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/tests/base.py, src/senaite/patient/tests/doctests/PatientWorkflow.rst, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
**☝️ Please merge #68 first**
This PR fixes the Patient Workflows to hide the global patent folder and the contained patients from client contact users.
Basically all logged in users could view the global patients folder and select any patient for their samples.
Patient folder can be only seen by the following roles: `LabManager`, `Manager`, `LabClerk`.
These roles can also create new patients.
If client local patients are enabled, the `Owner` roles can View/Edit local patients as well.
The `ClientGuest` role can only view, but not edit shared patients. 
--
=> Fix Patient Workflows and Permissions

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/widgets/agedob.py, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/content/fields.py, src/senaite/patient/monkeys/configure.zcml, src/senaite/patient/monkeys/content/analysisrequest.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/tests/doctests/API.rst, src/senaite/patient/tests/doctests/AgeDateOfBirthField.rst, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
> **Warning**
> Merge https://github.com/senaite/senaite.core/pull/2310 and https://github.com/senaite/senaite.core/pull/2311 first
This Pull Request makes `senaite.patient` compatible with https://github.com/senaite/senaite.core/pull/2307 and https://github.com/senaite/senaite.core/pull/2311 by replacing the `DateTimeField` type for sample's `DateOfBirth` to a new field `AgeDateOfBirthField`, fully supported by the `AgeDoBWidget`.
The "DateOfBirth" field was only storing the datetime, while other attributes required for the field and widget to work properly were stored as independent attributes in the instance itself.
The "DateOfBirth" field stores a tuple (`dob`, `from_age`, `estimated`).
--
and [Plone's …
=> Migrate sample's DateOfBirth field to AgeDateOfBirthField

docs/changelog.rst, src/senaite/patient/content/fields.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/tests/doctests/API.rst, src/senaite/patient/tests/doctests/AgeDateOfBirthField.rst, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
This Pull Request makes the system to automatically assign the OS's timezone to the Date of Birth if it is TZ-naive. This is especially important to guarantee that there are no inconsistencies when calculating age (that may cause an _inexplicable_ shift of 1d), amongst other reasons.
In addition, this makes the tests pass everywhere, regardless of the location of the machine running the tests.
Dates of birth that are timezone-naive are stored as-is
Current OS' TZ is used for when storeing Dates of birth that are TZ-naive
--
=> Use system's default timezone for TZ-naive birth dates

docs/changelog.rst, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This Pull Request fixes the traceback that arises for `AgeDoBWidget` when submitting the sample header form and a validator for a field other than `DateOfBirth` fails.
```
Traceback (most recent call last):
File "/home/senaite/buildout-cache/eggs/plone.app.viewletmanager-3.1.3-py2.7.egg/plone/app/viewletmanager/manager.py", line 110, in render
html.append(viewlet.render())
File "/home/senaite/zinstance/src/senaite.core/src/senaite/core/browser/viewlets/sampleheader.py", line 64, in render
return self.template(errors=errors)
File "/home/senaite/buildout-cache/eggs/Zope-4.8.7-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
return self.__func__(__self__, *args, **kw)
File "/home/senaite/buildout-cache/eggs/Zope-4.8.7-py2.7.egg/Products/Five/browser/pagetemplatefile …
```
=> Fix tracbeack on DateOfBirth update while validation fails for others

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/tests/doctests/API.rst
This Pull Request makes the `api.to_ymd` function to return a compliant ymd when no elapsed days
When no days elapsed, `to_ymd` returns an empty string
When no days elapsed, `to_ymd` returns `0d`, that is ymd-compliant
--
=> Make `to_ymd` return a compliant ymd when no elapsed days

docs/changelog.rst, src/senaite/patient/browser/widgets/agedob.py, src/senaite/patient/tests/doctests/PatientSample.rst
This Pull Request fixes a traceback that arises when creating partitions
```
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module ZPublisher.WSGIPublisher, line 288, in publish
Module bika.lims.browser.partition_magic, line 98, in __call__
Module bika.lims.utils.analysisrequest, line 434, in create_partition
Module bika.lims.utils.analysisrequest, line 92, in create_analysisrequest
Module Products.Archetypes.BaseObject, line 676, in processForm
Module Products.Archetypes.BaseObject, line 653, in _processForm
- __traceback_info__: (<AnalysisRequest at …
```
=> Fix traceback when creating partitions

src/senaite/patient/browser/controlpanel.py, src/senaite/patient/skins/templates/senaite_patient_widgets/temporaryidentifierwidget.pt
This Pull Request displays a message in red when no Medical Record Number on sample submit and patient's setting "Require Medical Record Number (MRN)" is enabled:
No error message after submit
Error message after submit
--
=> Display error when no value is entered for Medical Record Number

.github/workflows/build-and-test.yml
This PR fixes the failing GitHub action
Error occurs when running the GitHub action:
```
Error: The version '2.7.18' with architecture 'x64' was not found for Ubuntu 20.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
Action is running w/o errors
--
=> Fix failing GitHub Action

docs/changelog.rst, src/senaite/patient/browser/patient/views.py, src/senaite/patient/content/patient.py, src/senaite/patient/content/patientfolder.py
> [!WARNING]  
> **Merge https://github.com/senaite/senaite.core/pull/2370 first**
This PR fixes a side-effect of the portal-catalog patch introduced in https://github.com/senaite/senaite.core/pull/2368
Linked issue: https://github.com/senaite/senaite.patient/issues/
```
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module ZPublisher.WSGIPublisher, line 288, in publish
Module plone.z3cform.layout, line 63, in __call__
Module plone.z3cform.layout, line 47, in update
Module plone.dexterity.browser.add, line 138, in update
Module plone.z3cform.fieldsets.extensible, line 65, in …
```
=> Fix traceback when adding a patient

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/subscribers/analysisrequest.py
Patients are no longer created when submitted via Add Sample form
Patients are not created on Add sample form submit
Patients are created on Add sample form submit
--
=> Fix Patients are not created on Add Sample submit

docs/changelog.rst, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/content/patient.py, src/senaite/patient/i18n.py
When the configuration option "Require Medical Record Number (MRN)" is disabled, the "MRN" field in Patient add/edit view is not required and therefore, Patient objects with empty MRN can be created. In those cases, the internal ID of the patient is displayed in the patients listing.
This Pull Request displays "Not defined" instead of the object internal ID for patients with an empty MRN.
Patient internal id is displayed as MRN in listing for patients without MRN set.
"Not defined", along with an alert is displayed as MRN in listing for patients without MRN set
--
[2]: …
=> Display "Not defined" in listing for patients without MRN set

src/senaite/patient/content/analysisrequest.py
This PR removes the `display_template` introduced in https://github.com/senaite/senaite.patient/pull/85 to render the plain value in the samples MRN field.
`${mrn}` is displayed for the sample MRN field
The selected MRN value is displayed for the sample MRN field
--
=> Remove display_template from sample mrn

docs/changelog.rst, src/senaite/patient/browser/patient/samples.py
> [!WARNING]  
> **Review and merge https://github.com/senaite/senaite.app.listing/pull/118 first**
This Pull Request ensures that by default, the filter "All" is selected in samples listing from inside Patient. Reason is that we don't expect hundreds of samples from a Patient, but a few. Also, the samples listing in that context is commonly used for listing samples regardless of their status within the laboratory analysis workflow.
By default, system displays samples in "Active" status in Patient context
By default, system displays samples in "All" status in Patient context
--
[2]: …
=> Display all samples by default in Patient context

docs/changelog.rst, src/senaite/patient/content/patientfolder.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
This Pull Request removes the snapshots from `PatientFolder` and marks the object with `IDoNotSupportSnapshots` (and removes `IAuditable` marker as well).
System adds an snapshot for each modification of Patient folder, the addition of patients included
```
/home/senaite/buildout-cache/eggs/ZODB-5.8.0-py2.7.egg/ZODB/Connection.py:578: 
UserWarning: The <class 'persistent.list.PersistentList'> object
you're saving is large. (21919517 bytes.)
Perhaps you're storing media which should be stored in blobs.                                                                                               
Perhaps you're using a non-scalable data structure, such as a
PersistentMapping or PersistentList.
Perhaps you're storing data in objects that aren't persistent at
all. In cases like that, the data …
```
=> Fix addition of snapshots in PatientFolder on Patient creation

docs/changelog.rst, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/content/patient.py, src/senaite/patient/skins/templates/senaite_patient_widgets/agedobwidget.pt
This Pull Request makes `senaite.patient` compatible with https://github.com/senaite/senaite.core/pull/2399
`senaite.patient` is not compatible with latest datetimewidget changes
`senaite.patient` is compatible with latest datetimewidget changes
--
=> Compatibility with core#2399

docs/changelog.rst, src/senaite/patient/adapters/configure.zcml, src/senaite/patient/adapters/impress.py
This PR adds a `senaite.impress` group key provider that mixes in the Patient MRN to split reports.
Multiple patients are allowed in one (multi-)report PDF
Only 1 patient is allowed in one (multi-)report PDF
--
=> Allow only 1 Patient per Report

docs/changelog.rst, src/senaite/patient/catalog/configure.zcml, src/senaite/patient/catalog/indexer/__init__.py, src/senaite/patient/catalog/indexer/configure.zcml, src/senaite/patient/catalog/indexer/patient.py, src/senaite/patient/catalog/indexer/sample.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/upgrade/v01_04_000.py, src/senaite/patient/upgrade/v01_04_000.zcml
This Pull Request adds the MRN and Patient fullname as tokens into the existing `listing_searchable_text` index from samples catalog. Therefore, searches by MRN and patient name are suppported.
Is not possible to search samples by patient name or MRN
Is possible to search samples by patient name or MRN
--
=>   Allow searches by patient in samples listing 

docs/changelog.rst, src/senaite/patient/catalog/indexer/configure.zcml, src/senaite/patient/catalog/indexer/sample.py
**☝️ NOTE:** Please merge https://github.com/senaite/senaite.core/pull/2412 first!
This PR changes the listing searchable text adapter signature to include the request layer as well.
Listing searchable text adapter is *always* looked up, even if the add-on is not installed.
Listing searchable text adapter is *only* looked up, if the add-on is installed.
--
=> Layered listing searchable text adapter

docs/changelog.rst, src/senaite/patient/browser/patientfolder.py
This Pull Request makes the birth date to be displayed in patients listing
The birth date is not displayed in patients listing
The birth date is displayed in patients listing
--
=> Fix birth date is not displayed in patients listing

docs/changelog.rst, src/senaite/patient/browser/widgets/agedob.py
This Pull Request fixes an error that arises on sample creation when the field `DateOfBirth` is disabled from the sample add form via "Manage Form Fields".
```
Module bika.lims.decorators, line 51, in decorator
Module bika.lims.browser.analysisrequest.add2, line 708, in __call__
Module bika.lims.browser.analysisrequest.add2, line 1745, in ajax_submit
Module senaite.patient.browser.widgets.agedob, line 64, in process_form
AttributeError: 'str' object has no attribute 'get'
```
No traceback. The sample is created successfully
-- …
=> Fix AttributeError when DateOfBirth field is hidden in add sample

src/senaite/patient/browser/widgets/agedob.py
This Pull Request fixes a bug introduced with #100 so the date of birth is no longer saved when edited in Sample edit view.
Date of birth is not saved on sample view form submit
Date of birth is saved on sample view form submit
--
=> Fix date of birth is not saved on submit (sample view)

docs/changelog.rst, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/content/analysisrequest.py, src/senaite/patient/content/patient.py
No linked issue
Patient content type does not have a method collecting the birthdate of a patient as a string.  
Neither has Medical Record # field in Analysis Request form, a column with the birthdate,
Patient content type does have a method which collects the birthdate of a patient as a string and it applied where needed.
Add in Medical Record # field in Analysis Request form, a column with the birthdate,
--
=> Display birthdate in the pop-up for patient selection

docs/changelog.rst, src/senaite/patient/subscribers/analysisrequest.py, src/senaite/patient/tests/doctests/AgeDateOfBirthField.rst, src/senaite/patient/tests/doctests/DynamicResultRanges.rst, src/senaite/patient/tests/doctests/PatientSample.rst, src/senaite/patient/tests/doctests/PatientWorkflow.rst
This PR fixes a side-effect that the patient MRN is set to temporary when an Analyst enters results for sample analyses
Patient MRN is set to temporary
If the current user has no permission to create a patient, simply skip it.
--
=> Skip patient creation if the user has no permissions

docs/changelog.rst, src/senaite/patient/tests/doctests/DynamicResultRanges.rst
This Pull Request makes this product compatible with https://github.com/senaite/senaite.core/pull/2563
--
=> Compatibility with core#2563 (Move Dynamic Analysis Specs to Setup folder)

docs/changelog.rst, src/senaite/patient/api.py
This Pull Request makes the system to use system's default Timezone when calculating the date of birth via `api.get_birth_date` if no value for parameter `on_date` is explicitly set.
As a result, this fixes the following test:
https://github.com/senaite/senaite.patient/actions/runs/10426342600/job/28879098625#step:7:226
System does not take system's default TZ when calculating birthdate if `on_date` is not set
System does take system's default TZ when calculating birthdate if `on_date` is not set
--
=> Use default TZ when calculating birthdate if `on_date` param is not set

docs/changelog.rst, src/senaite/patient/api.py, src/senaite/patient/browser/patient/add2.py, src/senaite/patient/browser/patientfolder.py, src/senaite/patient/content/patient.py, src/senaite/patient/subscribers/analysisrequest.py
This Pull Request adds the field `estimated_birthdate` to `Patient` content type.
No "Estimated birthdate" field for `Patient` content type
"Estimated birthdate" field for `Patient` content type
--
=> Added estimated birthdate field to Patient content type

docs/changelog.rst, src/senaite/patient/adapters/listing.py
This Pull Request fixes a traceback that arises in samples listing when the sample does not have a MRN value set. Note [`getMedicalRecordNumberValue` accessor returns `None` if there is no value set for the field](https://github.com/senaite/senaite.patient/blob/77d6dcbc80a8a2440b1b7cdf8898e122ebe3e949/src/senaite/patient/monkeys/content/analysisrequest.py#L44).
```
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module ZPublisher.WSGIPublisher, line 288, in publish
Module senaite.app.listing.view, line 246, in __call__
Module senaite.app.listing.ajax, line 113, in handle_subpath …
```
=> Fix APIError: Expected string type in samples listing

docs/changelog.rst, src/senaite/patient/content/patient.py
This Pull Request makes the Patient's content accessor and mutator to rely on the core's base class instead of implemeting their own. Main reason is that base class takes fields from behaviors into account, while the current implementation doesn't. 
The Patient was migrated to folderish Content on https://github.com/senaite/senaite.patient/pull/24 . However, legacy accessor and mutator were kept.
Get an error when adding a new behavior relying on `context.accessor`
```python
@security.protected(permissions.View)
def getConsentSMS(self):
accessor = self.context.accessor("consent_sms")
return accessor(self.context)
```
```
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module …
```
=> Make accessor and mutator from Patient to rely on base class

docs/changelog.rst, src/senaite/patient/content/patient.py, src/senaite/patient/profiles/default/metadata.xml, src/senaite/patient/setuphandlers.py, src/senaite/patient/upgrade/v01_05_000.py, src/senaite/patient/upgrade/v01_05_000.zcml
> [!IMPORTANT]
> Merge https://github.com/senaite/senaite.core/pull/2681 first!
This Pull Request makes this product compatible with https://github.com/senaite/senaite.core/pull/2662
System relies on `_catalogs` attribute from `Patient` content type to know the catalogs to use
System relies on `catalog_mappings` from registry to know the catalogs to use
--
=> Rely on `catalog_mappings` to get the catalogs for Patient portal type

docs/changelog.rst, src/senaite/patient/adapters/listing.py
Linked issue: https://github.com/senaite/senaite.patient/issues/122
Patient is not hyperlinked on the Samples listing
Patient to be hyperlinked
--
=> Hyperlinked Patient on Sample listing

.github/workflows/build-and-test.yml, ci_flake8.cfg
This PR updates the GitHub action to use `ubuntu-latest`
Linked issue: https://github.com/senaite/senaite.patient/issues/
Ubuntu 20 is used with a Python 2.7 container
Ubuntu latest is used that installs Python 2.7 with PyEnv
--
=> Update Github Action

docs/changelog.rst, src/senaite/patient/adapters/configure.zcml, src/senaite/patient/adapters/form.py, src/senaite/patient/content/patient.py
> [!WARNING]
> Requirements:
> - https://github.com/senaite/senaite.core/pull/2695
> - https://github.com/senaite/senaite.core/pull/2705
This Pull Request adds age field and toggles age and birthdate field based on estimate birthday field
- The Patient content type does not support inputting age directly.
- Users are required to enter a birthdate, even if the birthdate is only estimated or unknown.
- A new field Age is added to the Patient content type.
- The user can input age either in: 
- A single number representing the number of years (e.g., 32y), or
- A structured format like Xy Ym Zd (e.g., 5y 2m 10d) — if supported.
- When the user selects the checkbox "Birthdate is estimated", the birthdate field becomes hidden and the Age field becomes visible
--
I confirm I have tested this PR …
=> Add Age field for patient content

docs/changelog.rst, src/senaite/patient/adapters/configure.zcml, src/senaite/patient/browser/patient/views.py
This PR implements a form adapter for the Patient add view that handles the toggle between birthdate and age fields
- No field visibility toggling between age and birthdate for Patient add view
- Can toggle between age and birthdate for Patient add view
--
=> Add adapter for patient add views
